server {
    listen 8081;
    root /usr/share/nginx/html;
    index index.html;

    location /images/ {
        try_files $uri =404;
    }

    location /links.json {
        try_files $uri =404;
    }

    location / {
        try_files $uri /index.html;
    }
}
